### ISSUE TITLE
Allow moving of several tileset patterns at once

### ISSUE THREAD

**Issue by alexander-b** [solarus-games/solarus-quest-editor#171]
It should be possible to mark several tileset patterns, and move them uniformly along x and/or y.

A motivating example of when this is useful: If you have a tileset with a roads row and a cliffs row, and then decide that you want to split up your roads row into two rows, one with the core roads and one with the roads' outlines, you might want the new tileset to have the roads' outlines row where the cliffs row used to be.

I.e.:
roads
cliffs

Becomes:
roads
roads-outlines
cliffs

And now you need to move all your cliffs patterns down e.g. 16px. This can be tedious if you have e.g. 3 patterns per cliff direction, and have four directions + corners.

You can of course do this in a text editor a bit more easily, but even there it's likely a bigger hassle than it should be.

So if we could just mark all the ill-placed cliff patterns, and drag them 16px down, it would save us a lot of time.

**Comment by Diarandor** [comment]
This issue is gonna be very helpful (as a huge time saver) for the development of our original tilesets, because we may need to relocate new tiles when these are added (if there is no space) or remove old tiles (so we need to remove the remaining gaps).

I am considering to relocate/add/remove tiles in our original overworld tileset, so this feature may help us a lot if you add it in some of the following snapshots (the sooner the better).

**Comment by Diarandor** [comment]
Could this be done for the end of this month or the beginning of the next month? I may need it for tileset creation (I don't want to waste time).

**Comment by christopho** [comment]
If anyone has time, contributions are welcome. @Maxs1789?

**Comment by christopho** [comment]
Thanks a lot @Maxs1789!

**Comment by Diarandor** [comment]
Thanks again @Maxs1789!
