### ISSUE TITLE
Feature: Allow the hero to go from a layer to another one without programming

### ISSUE THREAD

**Issue by maxamine** [solarus-games/solarus-quest-editor#269]
Add the up / down layers function in the properties of the sensors with the possibility of specifying the number of layers, in order to raise the hero of (n layer) without programming.

**Comment by christopho** [comment]
No, it existed like that in old versions, and it turned out that built-in behavior of sensors were not a great idea.
The script is very simple and can be made global to all maps thanks to metatables. Future versions of the Solarus ALTTP pack and of the initial quest will probably implement it. Then no more programming will be needed.

**Comment by christopho** [comment]
See https://github.com/solarus-games/solarus-quest-editor/issues/270

**Comment by maxamine** [comment]
ok i see. thanks ;-)
